<a href="https://colab.research.google.com/github/JoannaGrunwald/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Algebra liniowa](#a10)

### Podstawy

In [2]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size #liczba elementów

2

In [11]:
x.dtype #typ danych

dtype('int64')

2D Array

In [13]:
y = np.array([1.2, 3.4, 5.1])

In [14]:
y.dtype

dtype('float64')

In [16]:
z = np.array([[1, 2], [-9, 5]])

In [17]:
z.ndim

2

In [18]:
z.shape

(2, 2)

3D Array

In [20]:
x = np.array(
    [[[3, 4, 5], 
      [1, 2, 5]],

    [[4, 1, 3],
     [5, 2, 1]]]
)
x

array([[[3, 4, 5],
        [1, 2, 5]],

       [[4, 1, 3],
        [5, 2, 1]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(2, 2, 3)

Typy danych

In [4]:
A =  np.array([1, 2, 3])
A.dtype

dtype('int64')

In [5]:
A =  np.array([1, 2, 3], dtype = 'float')
A.dtype

dtype('float64')

In [6]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [8]:
A = np.array([24, 120, 230], dtype = np.uint8) #pikselowe opisywanie obrazów
A.dtype 

dtype('uint8')

Tworzenie tablic

In [9]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full(shape=(3,4), fill_value=4, dtype='int')

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.arange(start=5, stop=12, step=2)

array([ 5,  7,  9, 11])

In [20]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [21]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
A.reshape(5, -1) #-1 automatycznie dopiero drugi parametr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [25]:
A = np.array([3, 1, 2, 4])
B = np.array([1, -1, 4, 2])
print(A)
print(B)

[3 1 2 4]
[ 1 -1  4  2]


In [26]:
A + B

array([4, 0, 6, 6])

In [27]:
A - B

array([ 2,  2, -2,  2])

In [28]:
A * B 

array([ 3, -1,  8,  8])

In [29]:
A / B

array([ 3. , -1. ,  0.5,  2. ])

In [30]:
A + 3

array([6, 4, 5, 7])

In [31]:
B * 3

array([ 3, -3, 12,  6])

In [32]:
abs(B)

array([1, 1, 4, 2])

In [33]:
np.add(A,B)

array([4, 0, 6, 6])

In [35]:
np.subtract(A, B)

array([ 2,  2, -2,  2])

In [36]:
np.multiply(A, 2)

array([6, 2, 4, 8])

In [37]:
np.divide(B, -1)

array([-1.,  1., -4., -2.])

In [39]:
X = np.array([[1,3], [4,2]])
Y = np.array([[6,0], [-2,1]])
print(X)
print(Y)

[[1 3]
 [4 2]]
[[ 6  0]
 [-2  1]]


In [40]:
np.dot(X, Y) #mnożenie macierzowe

array([[ 0,  3],
       [20,  2]])

In [41]:
X.dot(Y)

array([[ 0,  3],
       [20,  2]])

In [42]:
Y.dot(X)

array([[ 6, 18],
       [ 2, -4]])

In [43]:
X @ Y

array([[ 0,  3],
       [20,  2]])

Generowanie liczb pseudolosowych

In [44]:
np.random.seed(0)

In [45]:
np.random.randn() #rozkład normalny

1.764052345967664

In [46]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [47]:
np.random.randn(10,3)

array([[ 1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297]])

In [48]:
np.random.rand(10) #rozkład jednostajny

array([0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559])

In [50]:
np.random.randint(15) #losowa liczba poniżej 15

13

In [52]:
np.random.randint(low=100, high=150, size=(2,3))

array([[148, 149, 105],
       [141, 135, 100]])

In [53]:
np.random.choice([4,6,1,3])

3

In [3]:
np.random.choice(['python','java', 'sql'])

'sql'

In [4]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.random.shuffle(data)

In [6]:
data

array([5, 3, 4, 0, 6, 2, 9, 7, 8, 1])

Podstawowe funkcje

In [7]:
np.exp(1)

2.718281828459045

In [8]:
np.sqrt(9)

3.0

In [9]:
np.all([2, 3, 1])

True

In [10]:
bool(0)

False

In [12]:
bool(2) #True dla wszystkiego innego niż 0

True

In [15]:
A = np.random.rand(5)
A

array([0.1444619 , 0.17435086, 0.63935262, 0.51878422, 0.8102865 ])

In [16]:
A[np.argmax(A)]

0.8102865046962028

In [17]:
A[np.argmin(A)]

0.14446190348053267

In [18]:
np.argmin(A)

0

In [19]:
np.argsort(A)

array([0, 1, 3, 2, 4])

In [20]:
A[np.argsort(A)]

array([0.1444619 , 0.17435086, 0.51878422, 0.63935262, 0.8102865 ])

In [21]:
np.mean(A)

0.4574472226333303

In [22]:
np.median(A)

0.5187842249703759

In [24]:
np.std(A)

0.26055737224930514

Indeksowanie, wycinanie

In [26]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [28]:
A[4]

4

In [29]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
A = A.reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
A[0]

array([0, 1, 2, 3])

In [35]:
A[:, 3]

array([ 3,  7, 11, 15, 19])

In [37]:
A[:, -1] #ostatnia, -2 przedostatnia, itd

array([ 3,  7, 11, 15, 19])

In [38]:
A[3,2]

14

In [41]:
A[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

Iteracja po tablicach

In [42]:
for row in A:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [43]:
for row in A:
  print(row[:3])

[0 1 2]
[4 5 6]
[ 8  9 10]
[12 13 14]
[16 17 18]


In [44]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [45]:
A.shape

(5, 4)

In [46]:
A.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
A.ravel #wypłaszczenie danych

<function ndarray.ravel>

In [48]:
A.T #transpozycja

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [49]:
A.T.shape

(4, 5)

Maski logiczne

In [57]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [53]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
A[A < 0] = 200 # zastąpienie wartości ujemnych przez 200
A

In [58]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.bitwise_or[]