<a href="https://colab.research.google.com/github/JoannaGrunwald/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Algebra liniowa](#a10)

### Podstawy

In [2]:
import numpy as np
np.__version__

'1.21.6'

Norma wektorowa

In [3]:
v1 = np.array([0,4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)

In [4]:
v2 = np.array([3,2,10])

In [5]:
np.linalg.norm(v2)

10.63014581273465

Odległość punktów

In [6]:
p = np.array([1,5])
q = np.array([2,-1])

np.linalg.norm(p-q)

6.082762530298219

Mnożenie macierzowe

In [8]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1], [-1]])

print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [10]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [11]:
Z.shape

(2, 1)

In [14]:
X.dot(Y)

array([[ 2],
       [-6]])

Wyznacznik

In [15]:
A = np.array([[2,4], [6,-1]])
A

array([[ 2,  4],
       [ 6, -1]])

In [19]:
round(np.linalg.det(A))

-26

Ślad macierzy - suma elementów na przekątnej

In [21]:
np.trace(A)

1

Macierz jednostkowa

In [22]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna i transponowana

In [26]:
np.linalg.inv(A)

array([[ 0.03846154,  0.15384615],
       [ 0.23076923, -0.07692308]])

In [29]:
np.transpose(A)

array([[ 2,  6],
       [ 4, -1]])

In [30]:
A.T

array([[ 2,  6],
       [ 4, -1]])

Rozwiązywanie układów równań

In [31]:
A = np.array([[2,4], [1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [33]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [34]:
A_inv = np.linalg.inv(A)

In [36]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [37]:
X.shape

(2, 1)